package API_Enums;

public enum Country {
    UNITED_ARAB_EMIRATES("ae"),
    ARGENTINA("ar"),
    AUSTRIA("at"),
    AUSTRALIA("au"),
    BELGIUM("be"),
    BULGARIA("bg"),
    BRAZIL("br"),
    CANADA("ca"),
    SWITZERLAND("ch"),
    CHINA("cn"),
    COLOMBIA("co"),
    CUBA("cu"),
    CZECH_REPUBLIC("cz"),
    GERMANY("de"),
    EGYPT("eg"),
    FRANCE("fr"),
    UNITED_KINGDOM("gb"),
    GREECE("gr"),
    HONGKONG("hk"),
    HUNGARY("hu"),
    INDONESIA("id"),
    IRELAND("ie"),
    ISRAEL("il"),
    INDIEN("in"),
    ITALY("it"),
    JAPAN("jp"),
    KOREA_SOUTH("kr"),
    LITHUANIA("lt"),
    LATIVA("lv"),
    MOROCCO("ma"),
    MEXICO("mx"),
    MALAYSIA("my"),
    NIGERIA("ng"),
    NETHERLANDS("nl"),
    NORWAY("no"),
    NEWZEALAND("nz"),
    PHILIPPINES("ph"),
    POLAND("pl"),
    PORTUGAL("pt"),
    ROMANIA("ro"),
    SERBIA("rs"),
    RUSSIA("ru"),
    SAUDIARABIA("sa"),
    SWEDEN("se"),
    SINGAPORE("sg"),
    SLOVENIA("si"),
    SLOVAKIA("sk"),
    THAILAND("th"),
    TURKY("tr"),
    TAIWAN("tw"),
    UKRAINE("au"),
    USA("us"),
    VENEZUELA("ve"),
    SOUTHAFRICA("za");


    public final String country;

    Country(String country) {
        this.country = country;
    }
}
